server:
  port: 8090

#logging:
#  level:
#    org:
#      springframework: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: validate
keycloak:
  auth-server-url: ${value.keycloak.url}
  realm: ${value.keycloak.realm}
  resource: ${value.client.id}
  public-client: true
  bearer-only: true
